#!/usr/bin/env python3
"""
Create a white-light FITS image from LEGUS filter FITS using pure Python.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
from astropy.io import fits


def find_filter_fits(gal_dir: Path) -> list[Path]:
    cands = [p for p in gal_dir.rglob("*.fits") if p.is_file()]
    cands = [p for p in cands if "downloads" not in p.parts]
    patt = re.compile(r"(f275w|f336w|f435w|f555w|f814w)", re.IGNORECASE)
    fits_sel = [p for p in cands if patt.search(p.name)]
    fits_sel = [p for p in fits_sel if "white" not in p.name.lower()]
    return sorted(fits_sel)


def make_white_from_filters(galaxy: str, gal_dir: Path) -> Path:
    files = find_filter_fits(gal_dir)
    if not files:
        raise RuntimeError(
            f"No filter FITS found under {gal_dir}. "
            "Expected files containing f275w/f336w/f435w/f555w/f814w."
        )

    arrays: list[np.ndarray] = []
    header0 = None
    shape0 = None
    for fp in files:
        with fits.open(fp) as hdul:
            hdu = hdul[0]
            data = np.asarray(hdu.data, dtype=float).squeeze()
            if data.ndim != 2:
                continue
            if header0 is None:
                header0 = hdu.header.copy()
                shape0 = data.shape
            if data.shape != shape0:
                continue
            arrays.append(data)

    if not arrays:
        raise RuntimeError("Found FITS files, but none had compatible 2D shapes for white image.")

    white = np.nanmean(np.stack(arrays, axis=0), axis=0)
    out = gal_dir / f"{galaxy}_white.fits"
    header0["HISTORY"] = "White image generated by make_white_light.py (nanmean over filters)."
    fits.PrimaryHDU(white.astype(np.float32), header=header0).writeto(out, overwrite=True)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Create white-light FITS from filter FITS (pure Python).")
    ap.add_argument("--galaxy", required=True, help="Galaxy/pointing id, e.g. ngc1313-e")
    ap.add_argument(
        "--project-root",
        default="/g/data/jh2/jt4478/comp_pipeline_restructure",
        help="Project root. Input/output under <project-root>/<galaxy>/",
    )
    args = ap.parse_args()

    galaxy = args.galaxy.strip().lower()
    gal_dir = (Path(args.project_root).expanduser().resolve() / galaxy).resolve()
    if not gal_dir.exists():
        raise RuntimeError(f"Galaxy directory not found: {gal_dir}")
    out = make_white_from_filters(galaxy, gal_dir)
    print(f"[white] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

