#!/usr/bin/env bash
set -euo pipefail

# Package this repository for HPC transfer.
# - minimal mode (default): code + docs + configs, excludes heavy data and outputs
# - full mode: includes project data needed to run immediately (can be very large)
#
# Usage:
#   bash scripts/package_for_hpc.sh
#   bash scripts/package_for_hpc.sh --mode full
#   bash scripts/package_for_hpc.sh --output /path/to/pkg.tar.gz

MODE="minimal"
OUT=""
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAMP="$(date +%Y%m%d_%H%M%S)"
TMP_DIR="$ROOT/.tmp_hpc_pkg_$STAMP"
STAGE_DIR="$TMP_DIR/comp_pipeline_restructure"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="${2:-}"
      shift 2
      ;;
    --output)
      OUT="${2:-}"
      shift 2
      ;;
    -h|--help)
      echo "Usage: bash scripts/package_for_hpc.sh [--mode minimal|full] [--output /abs/path/pkg.tar.gz]"
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

if [[ "$MODE" != "minimal" && "$MODE" != "full" ]]; then
  echo "--mode must be 'minimal' or 'full'" >&2
  exit 2
fi

if [[ -z "$OUT" ]]; then
  OUT="$ROOT/hpc_bundle_${MODE}_${STAMP}.tar.gz"
fi

rm -rf "$TMP_DIR"
mkdir -p "$STAGE_DIR"

echo "[1/3] Staging files ($MODE mode)..."
cd "$ROOT"

# Base excludes: transient, caches, VCS metadata, generated outputs
EXCLUDES=(
  "--exclude=.git"
  "--exclude=.idea"
  "--exclude=.cursor"
  "--exclude=.venv"
  "--exclude=venv"
  "--exclude=__pycache__"
  "--exclude=.pytest_cache"
  "--exclude=.mypy_cache"
  "--exclude=.ruff_cache"
  "--exclude=.DS_Store"
  # macOS AppleDouble / resource forks — break pip on Linux if packed or extracted
  "--exclude=**/._*"
  "--exclude=**/.AppleDouble"
  "--exclude=**/__MACOSX"
  # Regenerated by `pip install -e .` on HPC; packing stale/broken metadata confuses pip
  "--exclude=*.egg-info"
  "--exclude=*.egg-info/"
  "--exclude=*.pyc"
  "--exclude=*.pyo"
  "--exclude=*.swp"
  "--exclude=.tmp_hpc_pkg_*"
  "--exclude=tmp_pipeline_test"
  "--exclude=logs"
  "--exclude=nn_sweep_out"
  "--exclude=det_3d.npy"
  "--exclude=allprop.npz"
)

# Generated output dirs to skip in both modes
EXCLUDES+=(
  "--exclude=ngc628-c/white/baolab"
  "--exclude=ngc628-c/white/synthetic_frames"
  "--exclude=ngc628-c/white/synthetic_fits"
  "--exclude=ngc628-c/white/matched_coords"
  "--exclude=ngc628-c/white/detection_labels"
  "--exclude=ngc628-c/white/diagnostics"
  "--exclude=ngc628-c/white/catalogue"
  "--exclude=ngc628-c/white/s_extraction"
  "--exclude=ngc628-c/f275w/baolab"
  "--exclude=ngc628-c/f275w/synthetic_fits"
  "--exclude=ngc628-c/f275w/synthetic_frames"
  "--exclude=ngc628-c/f275w/s_extraction"
  "--exclude=ngc628-c/f275w/photometry"
  "--exclude=ngc628-c/f336w/baolab"
  "--exclude=ngc628-c/f336w/synthetic_fits"
  "--exclude=ngc628-c/f336w/synthetic_frames"
  "--exclude=ngc628-c/f336w/s_extraction"
  "--exclude=ngc628-c/f336w/photometry"
  "--exclude=ngc628-c/f435w/baolab"
  "--exclude=ngc628-c/f435w/synthetic_fits"
  "--exclude=ngc628-c/f435w/synthetic_frames"
  "--exclude=ngc628-c/f435w/s_extraction"
  "--exclude=ngc628-c/f435w/photometry"
  "--exclude=ngc628-c/f555w/baolab"
  "--exclude=ngc628-c/f555w/synthetic_fits"
  "--exclude=ngc628-c/f555w/synthetic_frames"
  "--exclude=ngc628-c/f555w/s_extraction"
  "--exclude=ngc628-c/f555w/photometry"
  "--exclude=ngc628-c/f814w/baolab"
  "--exclude=ngc628-c/f814w/synthetic_fits"
  "--exclude=ngc628-c/f814w/synthetic_frames"
  "--exclude=ngc628-c/f814w/s_extraction"
  "--exclude=ngc628-c/f814w/photometry"
  "--exclude=physprop"
)

if [[ "$MODE" == "minimal" ]]; then
  # Keep package small; user can rsync or symlink these large inputs on HPC.
  EXCLUDES+=(
    "--exclude=SLUG_library"
    "--exclude=PSF_files"
    "--exclude=output_lib"
    "--exclude=.deps"
    "--exclude=ngc628-c/*.fits"
    "--exclude=ngc628-c/*/*.fits"
    # Skip prior bundle artifacts inside the repo
    "--exclude=hpc_bundle_*.tar.gz"
    "--exclude=hpc_pipeline_bundle.zip"
  )
  # Exclude other galaxy trees (often huge); keep ngc628-c for sample configs/readme layout.
  for gal_dir in "$ROOT"/ngc*/; do
    [[ -d "$gal_dir" ]] || continue
    base="$(basename "$gal_dir")"
    [[ "$base" == "ngc628-c" ]] && continue
    EXCLUDES+=("--exclude=$base")
  done
fi

rsync -a "${EXCLUDES[@]}" "$ROOT/" "$STAGE_DIR/"

echo "[2/3] Writing README for HPC..."
cat > "$STAGE_DIR/HPC_PACKAGE_README.txt" <<EOF
HPC package mode: $MODE
Created: $(date)

Quick start on HPC:
1) tar -xzf $(basename "$OUT")
2) cd comp_pipeline_restructure
3) python3 -m venv .venv && source .venv/bin/activate
4) pip install -e .
5) bash scripts/package_for_hpc.sh --help   # package script is reusable
6) python scripts/check_pipeline_paths.py
7) python scripts/run_pipeline.py --check-only

Login-node quick test (venv + pip install -e . + checks):
  bash scripts/hpc_login_smoke_test.sh
  # See script header for COMP_* / GALAXY / CHECK_PHOTOMETRY overrides.

If MODE=minimal:
- Provide these paths on HPC (copy, symlink, or set env vars):
  - SLUG_library/
  - PSF_files/
  - .deps/local/bin/bl
  - ngc628-c science FITS
- See docs/RUNNING_ON_HPC.md for scheduler examples.

If pip fails with UnicodeDecodeError or mentions ._* or .egg-info:
  cd comp_pipeline_restructure
  find . -name '.DS_Store' -delete 2>/dev/null || true
  find . -name '._*' -delete 2>/dev/null || true
  rm -rf cluster_completeness_pipeline.egg-info .eggs
  rm -rf .venv && python3 -m venv .venv && source .venv/bin/activate
  pip install -e .
EOF

echo "[3/3] Creating tarball..."
mkdir -p "$(dirname "$OUT")"
tar -czf "$OUT" -C "$TMP_DIR" "comp_pipeline_restructure"

rm -rf "$TMP_DIR"
echo "Done: $OUT"
du -h "$OUT" | awk '{print "Size: "$1}'
